export const sampleCars = [
  {
    title: "2020 Hyundai Creta Restored",
    brand: "Hyundai",
    model: "Creta",
    year: 2020,
    price: 750000,
    originalPrice: 1200000,
    condition: "Excellent" as const,
    mileage: 45000,
    fuelType: "Petrol" as const,
    transmission: "Automatic" as const,
    city: "Krishnagiri",
    state: "Tamil Nadu",
    description: "Professionally restored Hyundai Creta with full repaint, new suspension components, and comprehensive mechanical overhaul. Looks and drives like new.",
    images: [
      "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800",
      "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800",
    ],
    featured: true,
    status: "available" as const,
    damageType: "Front End Collision",
    restorationStatus: "Fully Restored",
  },
  {
    title: "2019 Maruti Swift Dzire Refurbished",
    brand: "Maruti Suzuki",
    model: "Swift Dzire",
    year: 2019,
    price: 480000,
    originalPrice: 850000,
    condition: "Good" as const,
    mileage: 62000,
    fuelType: "Petrol" as const,
    transmission: "Manual" as const,
    city: "Krishnagiri",
    state: "Tamil Nadu",
    description: "Well-maintained Swift Dzire with minor bodywork repairs, fresh paint job, and serviced engine. Economical and reliable.",
    images: [
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800",
      "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800",
    ],
    featured: true,
    status: "available" as const,
    damageType: "Minor Scratches",
    restorationStatus: "Repaired & Repainted",
  },
  {
    title: "2021 Tata Nexon EV Restored",
    brand: "Tata",
    model: "Nexon EV",
    year: 2021,
    price: 1100000,
    originalPrice: 1600000,
    condition: "Excellent" as const,
    mileage: 28000,
    fuelType: "Electric" as const,
    transmission: "Automatic" as const,
    city: "Bangalore",
    state: "Karnataka",
    description: "Pristine Tata Nexon EV with battery health at 96%, full accident restoration, and factory-fresh appearance. Warranty transferable.",
    images: [
      "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800",
      "https://images.unsplash.com/photo-1680270406059-49b0b7f51093?w=800",
    ],
    featured: true,
    status: "available" as const,
    damageType: "Side Impact",
    restorationStatus: "Fully Restored",
  },
  {
    title: "2018 Honda City ZX Refurbished",
    brand: "Honda",
    model: "City ZX",
    year: 2018,
    price: 580000,
    originalPrice: 1050000,
    condition: "Good" as const,
    mileage: 78000,
    fuelType: "Petrol" as const,
    transmission: "Automatic" as const,
    city: "Chennai",
    state: "Tamil Nadu",
    description: "Top-variant Honda City with CVT transmission, full bodywork restoration, and renewed interiors. Premium sedan at an amazing price.",
    images: [
      "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800",
      "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800",
    ],
    featured: true,
    status: "available" as const,
    damageType: "Rear End Damage",
    restorationStatus: "Repaired",
  },
  {
    title: "2022 Mahindra Scorpio-N Restored",
    brand: "Mahindra",
    model: "Scorpio-N",
    year: 2022,
    price: 1450000,
    originalPrice: 2200000,
    condition: "Excellent" as const,
    mileage: 15000,
    fuelType: "Diesel" as const,
    transmission: "Automatic" as const,
    city: "Hyderabad",
    state: "Telangana",
    description: "Low-mileage Scorpio-N Z8L with full accident repair, fresh paint, and updated infotainment. Powerful SUV at the best price.",
    images: [
      "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=800",
      "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800",
    ],
    featured: true,
    status: "available" as const,
    damageType: "Flood Damage",
    restorationStatus: "Fully Restored",
  },
  {
    title: "2020 Kia Seltos HTX+ Restored",
    brand: "Kia",
    model: "Seltos HTX+",
    year: 2020,
    price: 920000,
    originalPrice: 1450000,
    condition: "Good" as const,
    mileage: 38000,
    fuelType: "Diesel" as const,
    transmission: "Manual" as const,
    city: "Coimbatore",
    state: "Tamil Nadu",
    description: "Feature-loaded Kia Seltos with panoramic sunroof, Bose audio, and full accident repair. Certified clean title after restoration.",
    images: [
      "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=800",
      "https://images.unsplash.com/photo-1551830820-330a71b99659?w=800",
    ],
    featured: false,
    status: "available" as const,
    damageType: "Front End Collision",
    restorationStatus: "Repaired & Repainted",
  },
];

export const sampleDealers = [
  {
    name: "Sri Venkateswara Auto Parts",
    contactPerson: "Rajesh Kumar",
    phone: "9876543210",
    email: "rajesh@svautokrishna.com",
    city: "Krishnagiri",
    state: "Tamil Nadu",
    specialization: ["Body Repair", "Painting", "Mechanical"],
    carTypes: ["Sedan", "SUV", "Hatchback"],
    rating: 4.8,
    status: "active" as const,
    notes: "Primary parts dealer for spare parts and body panels",
  },
  {
    name: "Chennai Auto Kingdom",
    contactPerson: "Suresh Babu",
    phone: "8765432109",
    email: "suresh@chennaiauto.com",
    city: "Chennai",
    state: "Tamil Nadu",
    specialization: ["Electrical", "AC Repair", "Mechanical"],
    carTypes: ["All Types"],
    rating: 4.5,
    status: "active" as const,
    notes: "Expert in electrical systems and air conditioning",
  },
  {
    name: "Bangalore Premium Motors",
    contactPerson: "Anand Rao",
    phone: "7654321098",
    email: "anand@bangaloremotor.com",
    city: "Bangalore",
    state: "Karnataka",
    specialization: ["Luxury Cars", "EVs", "Full Restoration"],
    carTypes: ["Luxury", "EV", "Sports"],
    rating: 4.9,
    status: "active" as const,
    notes: "Specializes in high-end car restoration",
  },
];
